### PR TITLE
Updated instructions in README

### PR DESCRIPTION
**Pull request by nicoloridulfo**
Seems like a verification of the code generation is needed before use.

### CODE REVIEW

**Comment by Qluxzz** [comment]
I went through the process of activating two factor authentication and I can indeed see that you now have to verify with the generated code once in order to finish the setup. 

But I think it would be better to remove the last sentence inside the parenthesis since there is no real requirement to generate the code via the code snippet rather than getting the code from an authenticator app for example.

I think: "Generate the TOTP code using the python code below and paste the TOTP code in the field below where you found the TOTP Secret." is sufficient.

**Comment by nicoloridulfo** [comment]
I was not able to use the TOTP Secret if it was not generated by the code. Did you?

See https://github.com/fhqvst/avanza
> 4. Finally, run node -e "console.log(require('avanza/dist/totp')('PASTE_YOUR_TOTP_SECRET_HERE'))" to generate an initial code.

However, feel free to change the text however you like. 

By the way,
Thank you for sharing this library. Truly beautiful pythonic code. I love this library!

**Comment by Qluxzz** [comment]
> I was not able to use the TOTP Secret if it was not generated by the code. Did you?

Yes, I used the built in TOPT-support in Bitwarden to get the code and it works as expected.

> However, feel free to change the text however you like.

Since, it's your PR you need to make the change and push the updated changes. I could close this PR and update it myself but I want you to get credit for it as well.

**Comment by nicoloridulfo** [comment]
Sådär!

**Pull request merged**
